/**
 * Equifax Report Context
 * 
 * Manages session-only storage of Equifax credit report data.
 * Used to pass parsed negative accounts to AI Agent for analysis.
 * 
 * Note: This is SESSION-ONLY storage (not persisted to DB).
 * Letters generated by AI Agent are routed to Dispute Tracker only.
 */

import React, { createContext, useContext, useState, useCallback } from "react";
import type {
  ParsedCreditReport,
  ParsedNegativeAccount,
} from "@/backend/equifax/equifax-client";

/**
 * State shape for Equifax report context (now supports multi-bureau)
 */
interface EquifaxReportState {
  /** Parsed credit report data (multi-bureau, AI-readable) */
  report: ParsedCreditReport | null;

  /** List of all negative accounts from all bureaus */
  negativeAccounts: ParsedNegativeAccount[];

  /** Whether report is currently being fetched */
  isLoading: boolean;

  /** Error message if fetch failed */
  error: string | null;

  /** Type of error for classification */
  errorType:
    | "AUTHENTICATION_ERROR"
    | "INVALID_CONSUMER_DATA"
    | "API_ERROR"
    | "PARSE_ERROR"
    | "UNKNOWN_ERROR"
    | null;

  /** ISO timestamp of last successful fetch */
  lastFetchedAt: string | null;

  /** Negative accounts organized by bureau */
  negativeAccountsByBureau: {
    equifax: ParsedNegativeAccount[];
    experian: ParsedNegativeAccount[];
    transunion: ParsedNegativeAccount[];
  };
}

/**
 * Context actions
 */
interface EquifaxReportActions {
  /** Set report data (called after successful tRPC fetch) */
  setReportData: (report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => void;

  /** Set error state (called after failed tRPC fetch) */
  setErrorData: (error: string, errorType: EquifaxReportState["errorType"]) => void;

  /** Clear report and error state */
  clearReport: () => void;

  /** Set loading state */
  setLoading: (loading: boolean) => void;
}

/**
 * Context type
 */
type EquifaxReportContextType = EquifaxReportState & EquifaxReportActions;

/**
 * Create context
 */
const EquifaxReportContext = createContext<EquifaxReportContextType | undefined>(undefined);

/**
 * Provider component
 */
export function EquifaxReportProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<EquifaxReportState>({
    report: null,
    negativeAccounts: [],
    isLoading: false,
    error: null,
    errorType: null,
    lastFetchedAt: null,
    negativeAccountsByBureau: {
      equifax: [],
      experian: [],
      transunion: [],
    },
  });

  // Internal helper: set report data
  const _setReportData = useCallback((report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => {
    // Organize accounts by bureau
    const byBureau = {
      equifax: accounts.filter((acc) => acc.bureau === "Equifax"),
      experian: accounts.filter((acc) => acc.bureau === "Experian"),
      transunion: accounts.filter((acc) => acc.bureau === "TransUnion"),
    };

    setState({
      report,
      negativeAccounts: accounts,
      isLoading: false,
      error: null,
      errorType: null,
      lastFetchedAt: new Date().toISOString(),
      negativeAccountsByBureau: byBureau,
    });
  }, []);

  // Internal helper: set error data
  const _setErrorData = useCallback(
    (error: string, errorType: EquifaxReportState["errorType"]) => {
      setState({
        report: null,
        negativeAccounts: [],
        isLoading: false,
        error,
        errorType,
        lastFetchedAt: null,
        negativeAccountsByBureau: {
          equifax: [],
          experian: [],
          transunion: [],
        },
      });
    },
    []
  );

  // Public API: set report data
  const setReportData = useCallback(
    (report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => {
      _setReportData(report, accounts);
    },
    [_setReportData]
  );

  // Public API: set error
  const setErrorData = useCallback(
    (error: string, errorType: EquifaxReportState["errorType"]) => {
      _setErrorData(error, errorType);
    },
    [_setErrorData]
  );

  // Public API: clear report
  const clearReport = useCallback(() => {
    setState({
      report: null,
      negativeAccounts: [],
      isLoading: false,
      error: null,
      errorType: null,
      lastFetchedAt: null,
      negativeAccountsByBureau: {
        equifax: [],
        experian: [],
        transunion: [],
      },
    });
  }, []);

  // Public API: set loading
  const setLoading = useCallback((loading: boolean) => {
    setState(prev => ({
      ...prev,
      isLoading: loading,
    }));
  }, []);

  const value: EquifaxReportContextType = {
    ...state,
    setReportData,
    setErrorData,
    clearReport,
    setLoading,
  };

  return (
    <EquifaxReportContext.Provider value={value}>
      {children}
    </EquifaxReportContext.Provider>
  );
}

/**
 * Hook to use Equifax report context
 */
export function useEquifaxReport(): EquifaxReportContextType {
  const context = useContext(EquifaxReportContext);
  if (!context) {
    throw new Error(
      "useEquifaxReport must be used within EquifaxReportProvider"
    );
  }
  return context;
}
