/**
 * Equifax Report Context
 *
 * Manages session-only storage of Equifax credit report + credit-monitoring
 * data pulled from the Equifax **Consumer Data Suite**:
 *   - Credit Reports    (POST /personal/consumer-data-suite/v1/creditReport)
 *   - Credit Monitoring (GET  /personal/consumer-data-suite/v1/creditMonitoring)
 *
 * Used to pass parsed negative accounts to the AI Agent for analysis and to
 * drive the summary report page + monitoring surface in the UI.
 *
 * Note: This is SESSION-ONLY storage (not persisted to DB).
 * Letters generated by AI Agent are routed to Dispute Tracker only.
 */

import React, { createContext, useContext, useState, useCallback } from "react";
import type {
  ParsedCreditReport,
  ParsedNegativeAccount,
  CreditReportSummary,
  CreditMonitoringResult,
} from "@/backend/equifax/equifax-client";

/**
 * Error type union shared by report + monitoring fetches.
 */
type EquifaxErrorType =
  | "AUTHENTICATION_ERROR"
  | "INVALID_CONSUMER_DATA"
  | "API_ERROR"
  | "PARSE_ERROR"
  | "UNKNOWN_ERROR"
  | null;

/**
 * State shape for Equifax report context (now supports multi-bureau + monitoring)
 */
interface EquifaxReportState {
  /** Parsed credit report data (multi-bureau, AI-readable) */
  report: ParsedCreditReport | null;

  /** List of all negative accounts from all bureaus */
  negativeAccounts: ParsedNegativeAccount[];

  /** Whether report is currently being fetched */
  isLoading: boolean;

  /** Error message if report fetch failed */
  error: string | null;

  /** Type of error for classification */
  errorType: EquifaxErrorType;

  /** ISO timestamp of last successful report fetch */
  lastFetchedAt: string | null;

  /** Negative accounts organized by bureau */
  negativeAccountsByBureau: {
    equifax: ParsedNegativeAccount[];
    experian: ParsedNegativeAccount[];
    transunion: ParsedNegativeAccount[];
  };

  // -------------------------------------------------------------------------
  // Credit monitoring
  // -------------------------------------------------------------------------

  /** Latest credit-monitoring result (alerts) */
  monitoring: CreditMonitoringResult | null;

  /** Whether monitoring alerts are currently being fetched */
  isMonitoringLoading: boolean;

  /** Error message if monitoring fetch failed */
  monitoringError: string | null;

  /** Type of error for monitoring fetch classification */
  monitoringErrorType: EquifaxErrorType;

  /** ISO timestamp of last successful monitoring fetch */
  lastMonitoringFetchedAt: string | null;
}

/**
 * Context actions
 */
interface EquifaxReportActions {
  /** Set report data (called after successful tRPC fetch) */
  setReportData: (report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => void;

  /** Set error state (called after failed tRPC fetch) */
  setErrorData: (error: string, errorType: EquifaxErrorType) => void;

  /** Clear report and error state */
  clearReport: () => void;

  /** Set loading state */
  setLoading: (loading: boolean) => void;

  /** Set monitoring data (called after successful monitoring fetch) */
  setMonitoringData: (monitoring: CreditMonitoringResult) => void;

  /** Set monitoring error state */
  setMonitoringError: (error: string, errorType: EquifaxErrorType) => void;

  /** Clear monitoring state */
  clearMonitoring: () => void;

  /** Set monitoring loading state */
  setMonitoringLoading: (loading: boolean) => void;

  /**
   * Convenience: the high-level summary for a given bureau (defaults to
   * Equifax). Returns null when no summary is available yet.
   */
  getSummary: (bureau?: "equifax" | "experian" | "transunion") => CreditReportSummary | null;
}

/**
 * Context type
 */
type EquifaxReportContextType = EquifaxReportState & EquifaxReportActions;

/**
 * Create context
 */
const EquifaxReportContext = createContext<EquifaxReportContextType | undefined>(undefined);

/**
 * Provider component
 */
export function EquifaxReportProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<EquifaxReportState>({
    report: null,
    negativeAccounts: [],
    isLoading: false,
    error: null,
    errorType: null,
    lastFetchedAt: null,
    negativeAccountsByBureau: {
      equifax: [],
      experian: [],
      transunion: [],
    },
    monitoring: null,
    isMonitoringLoading: false,
    monitoringError: null,
    monitoringErrorType: null,
    lastMonitoringFetchedAt: null,
  });

  // Internal helper: set report data
  const _setReportData = useCallback((report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => {
    // Organize accounts by bureau
    const byBureau = {
      equifax: accounts.filter((acc) => acc.bureau === "Equifax"),
      experian: accounts.filter((acc) => acc.bureau === "Experian"),
      transunion: accounts.filter((acc) => acc.bureau === "TransUnion"),
    };

    setState((prev) => ({
      ...prev,
      report,
      negativeAccounts: accounts,
      isLoading: false,
      error: null,
      errorType: null,
      lastFetchedAt: new Date().toISOString(),
      negativeAccountsByBureau: byBureau,
    }));
  }, []);

  // Internal helper: set error data
  const _setErrorData = useCallback(
    (error: string, errorType: EquifaxErrorType) => {
      setState((prev) => ({
        ...prev,
        report: null,
        negativeAccounts: [],
        isLoading: false,
        error,
        errorType,
        lastFetchedAt: null,
        negativeAccountsByBureau: {
          equifax: [],
          experian: [],
          transunion: [],
        },
      }));
    },
    []
  );

  // Public API: set report data
  const setReportData = useCallback(
    (report: ParsedCreditReport, accounts: ParsedNegativeAccount[]) => {
      _setReportData(report, accounts);
    },
    [_setReportData]
  );

  // Public API: set error
  const setErrorData = useCallback(
    (error: string, errorType: EquifaxErrorType) => {
      _setErrorData(error, errorType);
    },
    [_setErrorData]
  );

  // Public API: clear report
  const clearReport = useCallback(() => {
    setState((prev) => ({
      ...prev,
      report: null,
      negativeAccounts: [],
      isLoading: false,
      error: null,
      errorType: null,
      lastFetchedAt: null,
      negativeAccountsByBureau: {
        equifax: [],
        experian: [],
        transunion: [],
      },
    }));
  }, []);

  // Public API: set loading
  const setLoading = useCallback((loading: boolean) => {
    setState(prev => ({
      ...prev,
      isLoading: loading,
    }));
  }, []);

  // Public API: set monitoring data
  const setMonitoringData = useCallback((monitoring: CreditMonitoringResult) => {
    setState((prev) => ({
      ...prev,
      monitoring,
      isMonitoringLoading: false,
      monitoringError: null,
      monitoringErrorType: null,
      lastMonitoringFetchedAt: new Date().toISOString(),
    }));
  }, []);

  // Public API: set monitoring error
  const setMonitoringError = useCallback((error: string, errorType: EquifaxErrorType) => {
    setState((prev) => ({
      ...prev,
      isMonitoringLoading: false,
      monitoringError: error,
      monitoringErrorType: errorType,
    }));
  }, []);

  // Public API: clear monitoring
  const clearMonitoring = useCallback(() => {
    setState((prev) => ({
      ...prev,
      monitoring: null,
      isMonitoringLoading: false,
      monitoringError: null,
      monitoringErrorType: null,
      lastMonitoringFetchedAt: null,
    }));
  }, []);

  // Public API: set monitoring loading
  const setMonitoringLoading = useCallback((loading: boolean) => {
    setState((prev) => ({
      ...prev,
      isMonitoringLoading: loading,
    }));
  }, []);

  // Public API: get summary for a bureau
  const getSummary = useCallback(
    (bureau: "equifax" | "experian" | "transunion" = "equifax"): CreditReportSummary | null => {
      return state.report?.bureaus?.[bureau]?.summary ?? null;
    },
    [state.report]
  );

  const value: EquifaxReportContextType = {
    ...state,
    setReportData,
    setErrorData,
    clearReport,
    setLoading,
    setMonitoringData,
    setMonitoringError,
    clearMonitoring,
    setMonitoringLoading,
    getSummary,
  };

  return (
    <EquifaxReportContext.Provider value={value}>
      {children}
    </EquifaxReportContext.Provider>
  );
}

/**
 * Hook to use Equifax report context
 */
export function useEquifaxReport(): EquifaxReportContextType {
  const context = useContext(EquifaxReportContext);
  if (!context) {
    throw new Error(
      "useEquifaxReport must be used within EquifaxReportProvider"
    );
  }
  return context;
}
